import type {
  ReleaseIntakeDraftPayload,
  UploadedFileRef,
} from "../form-engine/types";

const coverFile: UploadedFileRef = {
  file_id: "mock-cover-low-spec",
  file_name: "aurora_leste_cover_1500.png",
  storage_bucket: "mock-covers",
  storage_path: "atabaque/drafts/mock-draft/cover/aurora_leste_cover_1500.png",
  public_url: "https://example.test/files/mock-cover-low-spec",
  download_url: "https://example.test/files/mock-cover-low-spec/download",
  mime_type: "image/png",
  size_bytes: 3_145_728,
};

const trackOneAudio: UploadedFileRef = {
  file_id: "mock-audio-track-1",
  file_name: "01_aurora_leste_master.wav",
  storage_bucket: "mock-audio",
  storage_path: "atabaque/drafts/mock-draft/audio/track-1/01_aurora_leste.wav",
  public_url: "https://example.test/files/mock-audio-track-1",
  download_url: "https://example.test/files/mock-audio-track-1/download",
  mime_type: "audio/wav",
  size_bytes: 48_234_111,
};

const trackTwoAudio: UploadedFileRef = {
  file_id: "mock-audio-track-2",
  file_name: "02_noite_clara_master.wav",
  storage_bucket: "mock-audio",
  storage_path: "atabaque/drafts/mock-draft/audio/track-2/02_noite_clara.wav",
  public_url: "https://example.test/files/mock-audio-track-2",
  download_url: "https://example.test/files/mock-audio-track-2/download",
  mime_type: "audio/wav",
  size_bytes: 44_980_200,
};

const additionalFile: UploadedFileRef = {
  file_id: "mock-asset-press-photo",
  file_name: "press_photo_demo.jpg",
  storage_bucket: "mock-assets",
  storage_path: "atabaque/drafts/mock-draft/assets/press_photo_demo.jpg",
  public_url: "https://example.test/files/mock-asset-press-photo",
  download_url: "https://example.test/files/mock-asset-press-photo/download",
  mime_type: "image/jpeg",
  size_bytes: 1_204_111,
};

export const releaseIntakeRuntimeDraftFixture = {
  draft_token: "mock-draft-token",
  workspace_slug: "atabaque",
  workflow_type: "release_intake",
  current_step: "review_submit",
  progress_percent: 83,
  values: {
    identification: {
      submitter_name: "Marina Oliveira",
      submitter_email: "marina@example.test",
      project_title: "Aurora Leste",
      release_type: "ep",
    },
    project: {
      release_date: "2026-09-18",
      genre: "MPB",
      explicit_content: "no",
      tiktok_snippet: "00:42-01:12",
      cover_link: "https://example.test/fallback-cover",
      promo_assets_link: "https://example.test/promo/aurora-leste",
      presskit_link: "https://example.test/presskit/aurora-leste",
      has_video_asset: "yes",
      video_link: "https://example.test/video/aurora-leste",
      video_release_date: "2026-09-20T10:00",
      cover_file: coverFile,
    },
    tracks: [
      {
        local_id: "track-1",
        client_track_id: "track-1",
        order_number: 1,
        title: "Aurora Leste",
        is_focus_track: true,
        primary_artists: "Marina Oliveira",
        featured_artists: "",
        interpreters: "Marina Oliveira",
        authors: "Marina Oliveira, Tiago Reis",
        publishers: "Demo Publishing",
        producers_musicians: "Tiago Reis",
        phonographic_producer: "Selo Demo",
        artist_profiles_status: "already_exists",
        artist_profile_names_to_create: "",
        existing_profile_links: "https://example.test/artists/marina",
        has_isrc: "yes",
        isrc_code: "BR-SBT-26-00001",
        explicit_content: "no",
        tiktok_snippet: "00:42-01:12",
        audio_file: trackOneAudio,
        lyrics: "Letra demo da faixa Aurora Leste.",
        track_status: "ready",
      },
      {
        local_id: "track-2",
        client_track_id: "track-2",
        order_number: 2,
        title: "Noite Clara",
        is_focus_track: false,
        primary_artists: "Marina Oliveira feat. Davi Costa",
        featured_artists: "Davi Costa",
        interpreters: "Marina Oliveira, Davi Costa",
        authors: "Marina Oliveira, Davi Costa",
        publishers: "Demo Publishing",
        producers_musicians: "Tiago Reis, Lia Prado",
        phonographic_producer: "Selo Demo",
        artist_profiles_status: "mixed",
        artist_profile_names_to_create: "Davi Costa",
        existing_profile_links: "https://example.test/artists/marina",
        has_isrc: "yes",
        isrc_code: "BR-SBT-26-00001",
        explicit_content: "no",
        tiktok_snippet: "01:04-01:34",
        audio_file: trackTwoAudio,
        lyrics: "Letra demo da faixa Noite Clara.",
        track_status: "draft",
      },
    ],
    marketing: {
      marketing_numbers: "10k seguidores combinados; campanha demo.",
      marketing_focus: "Fortalecer faixa foco no pre-save.",
      marketing_objectives: "Gerar awareness regional antes da data.",
      has_marketing_budget: "yes",
      marketing_budget: "R$ 4.000",
      focus_track_name: "Aurora Leste",
      date_flexibility: "Pode mover uma semana se necessario.",
      has_special_guests: "yes",
      special_guests_bio: "Davi Costa e convidado demo.",
      feat_will_promote: "yes",
      promotion_participants: "Marina Oliveira, Davi Costa",
      influencers_brands_partners: "Radio local demo; criadores independentes.",
      general_notes: "Observacoes gerais preservadas como project_notes.",
      additional_files: [additionalFile],
    },
  },
  meta: {
    form_version: "legacy_v1",
    source: "sunbeat.atabaque.release_intake.legacy_v1",
    updated_at: "2026-05-25T12:00:00.000Z",
  },
} satisfies ReleaseIntakeDraftPayload;
