export type ReleaseIntakeParityStatus =
  | "matched"
  | "partial"
  | "missing_in_schema"
  | "missing_in_runtime"
  | "visual_only"
  | "needs_decision";

export type ReleaseIntakeParityRisk = "low" | "medium" | "high";

export type ReleaseIntakeSchemaStepId =
  | "project"
  | "tracks"
  | "assets"
  | "review";

export type ReleaseIntakeRuntimeStepKey =
  | "identification"
  | "release"
  | "tracks"
  | "marketing"
  | "review_submit";

export type ReleaseIntakeRuntimeSurface =
  | "draft"
  | "submit"
  | "edit_mode"
  | "upload"
  | "airtable"
  | "drive"
  | "email"
  | "preview";

export type ReleaseIntakeParityEntry = {
  schemaFieldId: string | null;
  label: string;
  schemaStep: ReleaseIntakeSchemaStepId | null;
  runtimeStep: ReleaseIntakeRuntimeStepKey | null;
  runtimePayloadPath: string | null;
  status: ReleaseIntakeParityStatus;
  risk: ReleaseIntakeParityRisk;
  surfaces: readonly ReleaseIntakeRuntimeSurface[];
  notes: string;
};

export const releaseIntakeParityEntries = [
  {
    schemaFieldId: "submitter_name",
    label: "Submitter name",
    schemaStep: "project",
    runtimeStep: "identification",
    runtimePayloadPath: "identification.submitter_name",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "email"],
    notes: "Direct match with the active identification payload.",
  },
  {
    schemaFieldId: "submitter_email",
    label: "Submitter email",
    schemaStep: "project",
    runtimeStep: "identification",
    runtimePayloadPath: "identification.submitter_email",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "email"],
    notes: "Direct match; active submit normalizes the email to lowercase.",
  },
  {
    schemaFieldId: "project_title",
    label: "Project title",
    schemaStep: "project",
    runtimeStep: "identification",
    runtimePayloadPath: "identification.project_title",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "email"],
    notes: "Direct match with the active identification payload.",
  },
  {
    schemaFieldId: "primary_artist",
    label: "Project primary artist display",
    schemaStep: "project",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].primary_artists",
    status: "partial",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes:
      "Kept as a project-level display/AI-suggestion field. The runtime source of truth is now modeled separately as tracks[].primary_artists.",
  },
  {
    schemaFieldId: "release_type",
    label: "Release type",
    schemaStep: "project",
    runtimeStep: "identification",
    runtimePayloadPath: "identification.release_type",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "Direct match; active runtime also uses it for track count rules.",
  },
  {
    schemaFieldId: "release_date",
    label: "Release date",
    schemaStep: "project",
    runtimeStep: "release",
    runtimePayloadPath: "project.release_date",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes: "Direct match; active submit normalizes date strings.",
  },
  {
    schemaFieldId: "genre",
    label: "Genre",
    schemaStep: "project",
    runtimeStep: "release",
    runtimePayloadPath: "project.genre",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "Direct match with the active project payload.",
  },
  {
    schemaFieldId: "explicit_content",
    label: "Project explicit content",
    schemaStep: "project",
    runtimeStep: "release",
    runtimePayloadPath: "project.explicit_content",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes:
      "Preserved by the isolated adapter. Visible schema UI remains a later product decision.",
  },
  {
    schemaFieldId: "tiktok_snippet",
    label: "Project TikTok snippet",
    schemaStep: "project",
    runtimeStep: "release",
    runtimePayloadPath: "project.tiktok_snippet",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "PR20 adds the field to the candidate and preserves it in round-trip.",
  },
  {
    schemaFieldId: "has_video_asset",
    label: "Has video asset",
    schemaStep: "project",
    runtimeStep: "release",
    runtimePayloadPath: "project.has_video_asset",
    status: "matched",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode"],
    notes:
      "Value round-trips. Conditional visibility remains a renderer TODO because Form Schema v0 does not support visibleWhen.",
  },
  {
    schemaFieldId: "video_link",
    label: "Video link",
    schemaStep: "project",
    runtimeStep: "release",
    runtimePayloadPath: "project.video_link",
    status: "matched",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "drive"],
    notes: "Value round-trips as a string without calling any upload or Drive API.",
  },
  {
    schemaFieldId: "video_release_date",
    label: "Video release date",
    schemaStep: "project",
    runtimeStep: "release",
    runtimePayloadPath: "project.video_release_date",
    status: "matched",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode"],
    notes:
      "Value round-trips as text; datetime-specific rendering remains outside schema v0.",
  },
  {
    schemaFieldId: "project_notes",
    label: "Project notes",
    schemaStep: "project",
    runtimeStep: "marketing",
    runtimePayloadPath: "marketing.general_notes",
    status: "partial",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "email"],
    notes:
      "Closest runtime equivalent is marketing.general_notes, but product semantics still need confirmation before runtime binding.",
  },
  {
    schemaFieldId: "marketing.*",
    label: "Marketing fields carried by adapter",
    schemaStep: "project",
    runtimeStep: "marketing",
    runtimePayloadPath: "marketing",
    status: "partial",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "email"],
    notes:
      "The isolated adapter preserves runtime marketing fields, but the visible four-step candidate still does not add a dedicated marketing step.",
  },
  {
    schemaFieldId: "tracks",
    label: "Tracks repeater",
    schemaStep: "tracks",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[]",
    status: "partial",
    risk: "high",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes:
      "The candidate repeater covers the runtime fields needed for the PR20 round-trip, but profile-management and focus-track policies remain out of scope.",
  },
  {
    schemaFieldId: "tracks.title",
    label: "Track title",
    schemaStep: "tracks",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].title",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes: "Direct match with the active per-track payload.",
  },
  {
    schemaFieldId: "tracks.duration",
    label: "Track duration",
    schemaStep: "tracks",
    runtimeStep: null,
    runtimePayloadPath: null,
    status: "missing_in_runtime",
    risk: "low",
    surfaces: ["preview"],
    notes: "Visual-only candidate field; the active release_intake payload has no duration path.",
  },
  {
    schemaFieldId: "tracks.primary_artists",
    label: "Per-track primary artists",
    schemaStep: "tracks",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].primary_artists",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes:
      "PR20 separates this from project.primary_artist and preserves the per-track value in the adapter patch.",
  },
  {
    schemaFieldId: "tracks.featured_artists",
    label: "Featured artists",
    schemaStep: "tracks",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].featured_artists",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes: "Direct match with the active per-track payload.",
  },
  {
    schemaFieldId: "tracks.interpreters",
    label: "Interpreters",
    schemaStep: "tracks",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].interpreters",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes: "Direct match with the active per-track payload.",
  },
  {
    schemaFieldId: "tracks.authors",
    label: "Track authors",
    schemaStep: "tracks",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].authors",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes: "Direct match with the active per-track payload.",
  },
  {
    schemaFieldId: "tracks.publishers",
    label: "Publishers",
    schemaStep: "tracks",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].publishers",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes: "Direct match with the active per-track payload.",
  },
  {
    schemaFieldId: "tracks.producers_musicians",
    label: "Producers and musicians",
    schemaStep: "tracks",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].producers_musicians",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes: "Direct match with the active per-track payload.",
  },
  {
    schemaFieldId: "tracks.phonographic_producer",
    label: "Phonographic producer",
    schemaStep: "tracks",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].phonographic_producer",
    status: "matched",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes:
      "Field now round-trips. Active validation policy remains unchanged until submit parity.",
  },
  {
    schemaFieldId: "tracks.has_isrc",
    label: "Has ISRC",
    schemaStep: "tracks",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].has_isrc",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes: "Runtime uses this switch before serializing tracks[].isrc_code.",
  },
  {
    schemaFieldId: "tracks.isrc_code",
    label: "Track ISRC code",
    schemaStep: "tracks",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].isrc_code",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes:
      "The value round-trips; duplicate checks are derived into tracks[].validations only.",
  },
  {
    schemaFieldId: "tracks.explicit_content",
    label: "Track explicit content",
    schemaStep: "tracks",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].explicit_content",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes: "Direct match with the active per-track payload.",
  },
  {
    schemaFieldId: "tracks.tiktok_snippet",
    label: "Track TikTok snippet",
    schemaStep: "tracks",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].tiktok_snippet",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "Direct match with the active per-track payload.",
  },
  {
    schemaFieldId: "tracks.audio_file",
    label: "Per-track audio file",
    schemaStep: "tracks",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].audio_file",
    status: "visual_only",
    risk: "high",
    surfaces: ["preview", "upload", "drive"],
    notes:
      "Schema values preserve audio metadata per track. PR22 describes it in a pure upload manifest while keeping runtime upload disconnected.",
  },
  {
    schemaFieldId: "tracks.lyrics",
    label: "Lyrics",
    schemaStep: "tracks",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].lyrics",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "Direct match with the active per-track payload.",
  },
  {
    schemaFieldId: "tracks.validations",
    label: "Track validations",
    schemaStep: "tracks",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].isrc_code",
    status: "visual_only",
    risk: "high",
    surfaces: ["preview"],
    notes:
      "Computed schema-only object for ISRC/audio/credit blockers. Duplicate ISRC is derived as validations.err: isrc_duplicate and does not enter runtime patch.",
  },
  {
    schemaFieldId: "assets.cover_file",
    label: "Cover file",
    schemaStep: "assets",
    runtimeStep: "release",
    runtimePayloadPath: "project.cover_file",
    status: "visual_only",
    risk: "high",
    surfaces: ["preview", "upload", "drive"],
    notes:
      "Cover metadata can derive visual blockers and PR22 can describe it as a manifest candidate, but the actual file ref is excluded from patches.",
  },
  {
    schemaFieldId: "assets.cover_specs",
    label: "Cover specs",
    schemaStep: "assets",
    runtimeStep: "release",
    runtimePayloadPath: "project.cover_file",
    status: "visual_only",
    risk: "high",
    surfaces: ["preview", "upload"],
    notes:
      "Computed from cover_file width, height, dpi and status. It is never serialized into runtime draft patches.",
  },
  {
    schemaFieldId: "cover_link",
    label: "Cover link",
    schemaStep: "assets",
    runtimeStep: "release",
    runtimePayloadPath: "project.cover_link",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "drive"],
    notes: "Direct match for the runtime fallback cover URL.",
  },
  {
    schemaFieldId: "promo_assets_link",
    label: "Promo assets link",
    schemaStep: "assets",
    runtimeStep: "release",
    runtimePayloadPath: "project.promo_assets_link",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "drive"],
    notes: "Direct match with the active project payload.",
  },
  {
    schemaFieldId: "presskit_link",
    label: "Presskit link",
    schemaStep: "assets",
    runtimeStep: "release",
    runtimePayloadPath: "project.presskit_link",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "drive"],
    notes:
      "PR20 replaces the lossy boolean model with a URL/string field. Empty string remains an empty string.",
  },
  {
    schemaFieldId: "review",
    label: "Review summary",
    schemaStep: "review",
    runtimeStep: "review_submit",
    runtimePayloadPath: null,
    status: "visual_only",
    risk: "low",
    surfaces: ["preview"],
    notes:
      "The runtime review step is derived from form values and does not submit a review field.",
  },
  {
    schemaFieldId: "signal:artist-match",
    label: "Artist match AI signal",
    schemaStep: "project",
    runtimeStep: null,
    runtimePayloadPath: null,
    status: "visual_only",
    risk: "low",
    surfaces: ["preview"],
    notes:
      "Mock AI signal only; no active registry lookup or AI call exists in this PR.",
  },
  {
    schemaFieldId: "signal:date-conflict",
    label: "Date conflict warning",
    schemaStep: "project",
    runtimeStep: null,
    runtimePayloadPath: null,
    status: "visual_only",
    risk: "medium",
    surfaces: ["preview"],
    notes:
      "Mock warning only; connecting it would require a separate calendar/source decision.",
  },
  {
    schemaFieldId: "signal:isrc-duplicate-alert",
    label: "Duplicate ISRC blocker",
    schemaStep: "tracks",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].isrc_code",
    status: "needs_decision",
    risk: "high",
    surfaces: ["preview"],
    notes:
      "Derived in schema values, but active submit validation is not changed in this PR.",
  },
  {
    schemaFieldId: "signal:cover-spec-blocker",
    label: "Cover spec blocker",
    schemaStep: "assets",
    runtimeStep: "release",
    runtimePayloadPath: "project.cover_file",
    status: "needs_decision",
    risk: "high",
    surfaces: ["preview", "upload"],
    notes:
      "Derived from cover metadata in the adapter, but active upload validation is unchanged.",
  },
  {
    schemaFieldId: "signal:presskit-missing",
    label: "Missing presskit warning",
    schemaStep: "assets",
    runtimeStep: "release",
    runtimePayloadPath: "project.presskit_link",
    status: "visual_only",
    risk: "medium",
    surfaces: ["preview"],
    notes:
      "Mock warning only; runtime has a presskit link field but no warning decision model.",
  },
  {
    schemaFieldId: null,
    label: "Track order number",
    schemaStep: null,
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].order_number",
    status: "partial",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes:
      "Adapter carries order values, but the visible schema still relies on repeater order rather than a field.",
  },
  {
    schemaFieldId: null,
    label: "Focus track flag",
    schemaStep: null,
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].is_focus_track",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes: "Active runtime defaults the first track as focus; schema needs a policy.",
  },
  {
    schemaFieldId: null,
    label: "Artist profile status",
    schemaStep: null,
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].artist_profiles_status",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "Active conditional profile-management field remains outside PR20.",
  },
  {
    schemaFieldId: null,
    label: "Artist profiles to create",
    schemaStep: null,
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].artist_profile_names_to_create",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "Active conditional profile-management field remains outside PR20.",
  },
  {
    schemaFieldId: null,
    label: "Existing artist profile links",
    schemaStep: null,
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].existing_profile_links",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "Active conditional profile-management field remains outside PR20.",
  },
  {
    schemaFieldId: null,
    label: "Additional files",
    schemaStep: null,
    runtimeStep: "marketing",
    runtimePayloadPath: "marketing.additional_files",
    status: "missing_in_schema",
    risk: "high",
    surfaces: ["draft", "submit", "edit_mode", "upload", "drive"],
    notes:
      "Active asset upload list remains runtime-only; PR22 can carry explicit fixture metadata without adding it to schema values.",
  },
] as const satisfies readonly ReleaseIntakeParityEntry[];
