export type ReleaseIntakeParityStatus =
  | "matched"
  | "partial"
  | "missing_in_schema"
  | "missing_in_runtime"
  | "visual_only"
  | "needs_decision";

export type ReleaseIntakeParityRisk = "low" | "medium" | "high";

export type ReleaseIntakeSchemaStepId =
  | "project"
  | "tracks"
  | "assets"
  | "review";

export type ReleaseIntakeRuntimeStepKey =
  | "identification"
  | "release"
  | "tracks"
  | "marketing"
  | "review_submit";

export type ReleaseIntakeRuntimeSurface =
  | "draft"
  | "submit"
  | "edit_mode"
  | "upload"
  | "airtable"
  | "drive"
  | "email"
  | "preview";

export type ReleaseIntakeParityEntry = {
  schemaFieldId: string | null;
  label: string;
  schemaStep: ReleaseIntakeSchemaStepId | null;
  runtimeStep: ReleaseIntakeRuntimeStepKey | null;
  runtimePayloadPath: string | null;
  status: ReleaseIntakeParityStatus;
  risk: ReleaseIntakeParityRisk;
  surfaces: readonly ReleaseIntakeRuntimeSurface[];
  notes: string;
};

export const releaseIntakeParityEntries = [
  {
    schemaFieldId: "submitter_name",
    label: "Submitter name",
    schemaStep: "project",
    runtimeStep: "identification",
    runtimePayloadPath: "identification.submitter_name",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "email"],
    notes: "Direct match with the active identification payload.",
  },
  {
    schemaFieldId: "submitter_email",
    label: "Submitter email",
    schemaStep: "project",
    runtimeStep: "identification",
    runtimePayloadPath: "identification.submitter_email",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "email"],
    notes: "Direct match; active submit normalizes the email to lowercase.",
  },
  {
    schemaFieldId: "project_title",
    label: "Project title",
    schemaStep: "project",
    runtimeStep: "identification",
    runtimePayloadPath: "identification.project_title",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "email"],
    notes: "Direct match with the active identification payload.",
  },
  {
    schemaFieldId: "primary_artist",
    label: "Primary artist",
    schemaStep: "project",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].primary_artists",
    status: "partial",
    risk: "high",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes:
      "The candidate uses one project-level artist field, while the active runtime stores primary artists per track.",
  },
  {
    schemaFieldId: "release_type",
    label: "Release type",
    schemaStep: "project",
    runtimeStep: "identification",
    runtimePayloadPath: "identification.release_type",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "Direct match; active runtime also uses it for track count rules.",
  },
  {
    schemaFieldId: "release_date",
    label: "Release date",
    schemaStep: "project",
    runtimeStep: "release",
    runtimePayloadPath: "project.release_date",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes: "Direct match; active submit normalizes date strings.",
  },
  {
    schemaFieldId: "genre",
    label: "Genre",
    schemaStep: "project",
    runtimeStep: "release",
    runtimePayloadPath: "project.genre",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "Direct match with the active project payload.",
  },
  {
    schemaFieldId: "project_notes",
    label: "Project notes",
    schemaStep: "project",
    runtimeStep: "marketing",
    runtimePayloadPath: "marketing.general_notes",
    status: "partial",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode"],
    notes:
      "Closest runtime equivalent is marketing.general_notes, but this needs product confirmation before runtime binding.",
  },
  {
    schemaFieldId: "tracks",
    label: "Tracks repeater",
    schemaStep: "tracks",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[]",
    status: "partial",
    risk: "high",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes:
      "The candidate repeater covers a subset of the active TrackInput contract.",
  },
  {
    schemaFieldId: "tracks.title",
    label: "Track title",
    schemaStep: "tracks",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].title",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes: "Direct match with the active per-track payload.",
  },
  {
    schemaFieldId: "tracks.duration",
    label: "Track duration",
    schemaStep: "tracks",
    runtimeStep: null,
    runtimePayloadPath: null,
    status: "missing_in_runtime",
    risk: "low",
    surfaces: ["preview"],
    notes:
      "Visual-only candidate field; the active release_intake payload has no duration path.",
  },
  {
    schemaFieldId: "tracks.isrc_code",
    label: "Track ISRC code",
    schemaStep: "tracks",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].isrc_code",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes:
      "Runtime only submits the code when tracks[].has_isrc is yes, which is not modeled in the candidate yet.",
  },
  {
    schemaFieldId: "tracks.authors",
    label: "Track authors",
    schemaStep: "tracks",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].authors",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes: "Direct match with the active per-track payload.",
  },
  {
    schemaFieldId: "cover_file",
    label: "Cover file",
    schemaStep: "assets",
    runtimeStep: "release",
    runtimePayloadPath: "project.cover_file",
    status: "matched",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "upload", "drive"],
    notes:
      "The field path matches, but runtime binding must keep the existing signed upload flow.",
  },
  {
    schemaFieldId: "audio_files",
    label: "Audio files",
    schemaStep: "assets",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].audio_file",
    status: "partial",
    risk: "high",
    surfaces: ["draft", "submit", "edit_mode", "upload", "drive"],
    notes:
      "The candidate aggregates masters in the assets step; the active runtime stores audio per track.",
  },
  {
    schemaFieldId: "promo_assets_link",
    label: "Promo assets link",
    schemaStep: "assets",
    runtimeStep: "release",
    runtimePayloadPath: "project.promo_assets_link",
    status: "matched",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "drive"],
    notes: "Direct match with the active project payload.",
  },
  {
    schemaFieldId: "presskit_available",
    label: "Presskit available",
    schemaStep: "assets",
    runtimeStep: "release",
    runtimePayloadPath: "project.presskit_link",
    status: "partial",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "drive"],
    notes:
      "The candidate models a boolean state, while the active runtime stores a presskit link.",
  },
  {
    schemaFieldId: "review",
    label: "Review summary",
    schemaStep: "review",
    runtimeStep: "review_submit",
    runtimePayloadPath: null,
    status: "visual_only",
    risk: "low",
    surfaces: ["preview"],
    notes:
      "The runtime review step is derived from form values and does not submit a review field.",
  },
  {
    schemaFieldId: "signal:artist-match",
    label: "Artist match AI signal",
    schemaStep: "project",
    runtimeStep: null,
    runtimePayloadPath: null,
    status: "visual_only",
    risk: "low",
    surfaces: ["preview"],
    notes:
      "Mock AI signal only; no active registry lookup or AI call exists in this PR.",
  },
  {
    schemaFieldId: "signal:date-conflict",
    label: "Date conflict warning",
    schemaStep: "project",
    runtimeStep: null,
    runtimePayloadPath: null,
    status: "visual_only",
    risk: "medium",
    surfaces: ["preview"],
    notes:
      "Mock warning only; connecting it would require a separate calendar/source decision.",
  },
  {
    schemaFieldId: "signal:isrc-duplicate-alert",
    label: "Duplicate ISRC blocker",
    schemaStep: "tracks",
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].isrc_code",
    status: "needs_decision",
    risk: "high",
    surfaces: ["preview"],
    notes:
      "The visual blocker exists in the candidate, but active runtime validation does not yet enforce duplicate ISRC checks.",
  },
  {
    schemaFieldId: "signal:cover-spec-blocker",
    label: "Cover spec blocker",
    schemaStep: "assets",
    runtimeStep: "release",
    runtimePayloadPath: "project.cover_file",
    status: "needs_decision",
    risk: "high",
    surfaces: ["preview", "upload"],
    notes:
      "The visual blocker exists in the candidate, but active upload validation currently checks type and size, not image dimensions.",
  },
  {
    schemaFieldId: "signal:presskit-missing",
    label: "Missing presskit warning",
    schemaStep: "assets",
    runtimeStep: "release",
    runtimePayloadPath: "project.presskit_link",
    status: "visual_only",
    risk: "medium",
    surfaces: ["preview"],
    notes:
      "Mock warning only; runtime has a presskit link field but no warning decision model.",
  },
  {
    schemaFieldId: null,
    label: "Explicit content",
    schemaStep: null,
    runtimeStep: "release",
    runtimePayloadPath: "project.explicit_content",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes: "Active project field absent from the candidate schema.",
  },
  {
    schemaFieldId: null,
    label: "Project TikTok snippet",
    schemaStep: null,
    runtimeStep: "release",
    runtimePayloadPath: "project.tiktok_snippet",
    status: "missing_in_schema",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "Active project field absent from the candidate schema.",
  },
  {
    schemaFieldId: null,
    label: "Cover link",
    schemaStep: null,
    runtimeStep: "release",
    runtimePayloadPath: "project.cover_link",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "drive"],
    notes:
      "Active runtime supports a link fallback in addition to cover_file.",
  },
  {
    schemaFieldId: null,
    label: "Presskit link",
    schemaStep: null,
    runtimeStep: "release",
    runtimePayloadPath: "project.presskit_link",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "drive"],
    notes:
      "Candidate uses presskit_available; runtime stores the actual link.",
  },
  {
    schemaFieldId: null,
    label: "Has video asset",
    schemaStep: null,
    runtimeStep: "release",
    runtimePayloadPath: "project.has_video_asset",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "Controls conditional video fields in the active runtime.",
  },
  {
    schemaFieldId: null,
    label: "Video link",
    schemaStep: null,
    runtimeStep: "release",
    runtimePayloadPath: "project.video_link",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "drive"],
    notes: "Conditional active project field absent from the candidate schema.",
  },
  {
    schemaFieldId: null,
    label: "Video release date",
    schemaStep: null,
    runtimeStep: "release",
    runtimePayloadPath: "project.video_release_date",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "Conditional active project field absent from the candidate schema.",
  },
  {
    schemaFieldId: null,
    label: "Track order number",
    schemaStep: null,
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].order_number",
    status: "partial",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes: "Can be derived from repeater order, but the schema does not model it.",
  },
  {
    schemaFieldId: null,
    label: "Focus track flag",
    schemaStep: null,
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].is_focus_track",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes: "Active runtime defaults the first track as focus; schema needs a policy.",
  },
  {
    schemaFieldId: null,
    label: "Per-track primary artists",
    schemaStep: null,
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].primary_artists",
    status: "partial",
    risk: "high",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes:
      "Candidate has a project-level primary_artist but not the active per-track field.",
  },
  {
    schemaFieldId: null,
    label: "Featured artists",
    schemaStep: null,
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].featured_artists",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes: "Active credit field absent from the candidate schema.",
  },
  {
    schemaFieldId: null,
    label: "Interpreters",
    schemaStep: null,
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].interpreters",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes: "Active credit field absent from the candidate schema.",
  },
  {
    schemaFieldId: null,
    label: "Publishers",
    schemaStep: null,
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].publishers",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes: "Active rights/credit field absent from the candidate schema.",
  },
  {
    schemaFieldId: null,
    label: "Producers and musicians",
    schemaStep: null,
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].producers_musicians",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes: "Active credit field absent from the candidate schema.",
  },
  {
    schemaFieldId: null,
    label: "Phonographic producer",
    schemaStep: null,
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].phonographic_producer",
    status: "missing_in_schema",
    risk: "high",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes: "Active validation can require this when ISRC is present.",
  },
  {
    schemaFieldId: null,
    label: "Artist profile status",
    schemaStep: null,
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].artist_profiles_status",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "Active conditional profile-management field absent from schema.",
  },
  {
    schemaFieldId: null,
    label: "Artist profiles to create",
    schemaStep: null,
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].artist_profile_names_to_create",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "Active conditional profile-management field absent from schema.",
  },
  {
    schemaFieldId: null,
    label: "Existing artist profile links",
    schemaStep: null,
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].existing_profile_links",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "Active conditional profile-management field absent from schema.",
  },
  {
    schemaFieldId: null,
    label: "Has ISRC",
    schemaStep: null,
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].has_isrc",
    status: "missing_in_schema",
    risk: "high",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes:
      "Runtime uses this to decide whether tracks[].isrc_code is submitted.",
  },
  {
    schemaFieldId: null,
    label: "Track explicit content",
    schemaStep: null,
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].explicit_content",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "airtable"],
    notes: "Active per-track field absent from the candidate schema.",
  },
  {
    schemaFieldId: null,
    label: "Track TikTok snippet",
    schemaStep: null,
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].tiktok_snippet",
    status: "missing_in_schema",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "Active per-track field absent from the candidate schema.",
  },
  {
    schemaFieldId: null,
    label: "Per-track audio file",
    schemaStep: null,
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].audio_file",
    status: "partial",
    risk: "high",
    surfaces: ["draft", "submit", "edit_mode", "upload", "drive"],
    notes:
      "Candidate has audio_files as an aggregate upload placeholder, not per-track audio_file.",
  },
  {
    schemaFieldId: null,
    label: "Lyrics",
    schemaStep: null,
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].lyrics",
    status: "missing_in_schema",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "Active per-track field absent from the candidate schema.",
  },
  {
    schemaFieldId: null,
    label: "Track status",
    schemaStep: null,
    runtimeStep: "tracks",
    runtimePayloadPath: "tracks[].track_status",
    status: "missing_in_schema",
    risk: "low",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "Active internal track status is not modeled in schema v0.",
  },
  {
    schemaFieldId: null,
    label: "Marketing numbers",
    schemaStep: null,
    runtimeStep: "marketing",
    runtimePayloadPath: "marketing.marketing_numbers",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "email"],
    notes: "Active marketing field absent from the candidate schema.",
  },
  {
    schemaFieldId: null,
    label: "Marketing focus",
    schemaStep: null,
    runtimeStep: "marketing",
    runtimePayloadPath: "marketing.marketing_focus",
    status: "missing_in_schema",
    risk: "high",
    surfaces: ["draft", "submit", "edit_mode", "email"],
    notes: "Active progress calculation checks this field.",
  },
  {
    schemaFieldId: null,
    label: "Marketing objectives",
    schemaStep: null,
    runtimeStep: "marketing",
    runtimePayloadPath: "marketing.marketing_objectives",
    status: "missing_in_schema",
    risk: "high",
    surfaces: ["draft", "submit", "edit_mode", "email"],
    notes: "Active progress calculation checks this field.",
  },
  {
    schemaFieldId: null,
    label: "Has marketing budget",
    schemaStep: null,
    runtimeStep: "marketing",
    runtimePayloadPath: "marketing.has_marketing_budget",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "Controls a conditional active marketing field.",
  },
  {
    schemaFieldId: null,
    label: "Marketing budget",
    schemaStep: null,
    runtimeStep: "marketing",
    runtimePayloadPath: "marketing.marketing_budget",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "Conditional active marketing field absent from schema.",
  },
  {
    schemaFieldId: null,
    label: "Focus track name",
    schemaStep: null,
    runtimeStep: "marketing",
    runtimePayloadPath: "marketing.focus_track_name",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "Conditional active marketing field for EP/album releases.",
  },
  {
    schemaFieldId: null,
    label: "Date flexibility",
    schemaStep: null,
    runtimeStep: "marketing",
    runtimePayloadPath: "marketing.date_flexibility",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "email"],
    notes: "Active marketing planning field absent from schema.",
  },
  {
    schemaFieldId: null,
    label: "Has special guests",
    schemaStep: null,
    runtimeStep: "marketing",
    runtimePayloadPath: "marketing.has_special_guests",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode"],
    notes: "Controls conditional active marketing fields.",
  },
  {
    schemaFieldId: null,
    label: "Special guests bio",
    schemaStep: null,
    runtimeStep: "marketing",
    runtimePayloadPath: "marketing.special_guests_bio",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "email"],
    notes: "Conditional active marketing field absent from schema.",
  },
  {
    schemaFieldId: null,
    label: "Featured artist promotion commitment",
    schemaStep: null,
    runtimeStep: "marketing",
    runtimePayloadPath: "marketing.feat_will_promote",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "email"],
    notes: "Conditional active marketing field absent from schema.",
  },
  {
    schemaFieldId: null,
    label: "Promotion participants",
    schemaStep: null,
    runtimeStep: "marketing",
    runtimePayloadPath: "marketing.promotion_participants",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "email"],
    notes: "Active marketing field absent from the candidate schema.",
  },
  {
    schemaFieldId: null,
    label: "Influencers, brands and partners",
    schemaStep: null,
    runtimeStep: "marketing",
    runtimePayloadPath: "marketing.influencers_brands_partners",
    status: "missing_in_schema",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "email"],
    notes: "Active marketing field absent from the candidate schema.",
  },
  {
    schemaFieldId: null,
    label: "Marketing general notes",
    schemaStep: null,
    runtimeStep: "marketing",
    runtimePayloadPath: "marketing.general_notes",
    status: "partial",
    risk: "medium",
    surfaces: ["draft", "submit", "edit_mode", "email"],
    notes:
      "Candidate project_notes could map here, but that alias needs product confirmation.",
  },
  {
    schemaFieldId: null,
    label: "Additional files",
    schemaStep: null,
    runtimeStep: "marketing",
    runtimePayloadPath: "marketing.additional_files",
    status: "missing_in_schema",
    risk: "high",
    surfaces: ["draft", "submit", "edit_mode", "upload", "drive"],
    notes: "Active asset upload list absent from the candidate schema.",
  },
] as const satisfies readonly ReleaseIntakeParityEntry[];

