import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <script
  type="application/ld+json"
  dangerouslySetInnerHTML={{
    __html: JSON.stringify({
      "@context": "https://schema.org",
      "@type": "SoftwareApplication",
      name: "Sunbeat",
      applicationCategory: "BusinessApplication",
      operatingSystem: "Web",
      description:
        "Metadata-grade release intake platform for record labels with Airtable-native workflows, draft versioning and edit-mode via email.",
      offers: {
        "@type": "Offer",
        price: "0",
        priceCurrency: "USD"
      }
    })
  }}
/>
      </body>
    </html>
  );
}
